#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

cp -a $OPENSHIFT_REPO_DIR/nginx.conf $OPENSHIFT_DATA_DIR/conf/nginx.conf
sed -i.bak "s/NGINX_IP_PORT/$OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT/" $OPENSHIFT_DATA_DIR/conf/nginx.conf
sed -i.bak "s/YOSE_CLIENT/yoseclient-happydev.rhcloud.com/g" $OPENSHIFT_DATA_DIR/conf/nginx.conf
sed -i.bak "s/YOSE_NODE/yosenode-happydev.rhcloud.com/g" $OPENSHIFT_DATA_DIR/conf/nginx.conf

nohup $OPENSHIFT_DATA_DIR/sbin/nginx > $OPENSHIFT_DIY_LOG_DIR/server.log 2>&1 &
