#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

sed -e "s/`echo '$OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT'`/`echo $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT`/" $OPENSHIFT_REPO_DIR/nginx.conf > $OPENSHIFT_DATA_DIR/conf/nginx.conf

nohup $OPENSHIFT_DATA_DIR/sbin/nginx > $OPENSHIFT_DIY_LOG_DIR/server.log 2>&1 &
